version: '3.8'

services:
#  jmdc-webapp:
#    build: .
#    volumes:
#      - '.:/jmdc'
#    ports:
#      - 2022:2022
  jmdc-webapp:
    build: .
    command: /bin/bash -c "service lighttpd start && tail -f /dev/null"
    volumes:
      - ./etc/conf:/etc/lighttpd
      - /etc/hosts:/etc/hosts:ro
      - .:/jmdc
    restart: always
    ports:
      - 2022:80

